<a href="https://colab.research.google.com/github/ccy-nikename/pel/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import copy

class Vertex(object):
	"""docstring for Vertex"""
	def __init__(self, num, val):
		self.num = num
		self.val = val

class Graph_matrix(object):
	"""docstring for Graph"""
	def __init__(self):
		self.VerList = {}
		self.Adj_matrix = None

	#新增一个点
	def addVertex(self, num, val=None):
		ver = Vertex(num, val)
		self.VerList[ver.num] = ver.val
		if len(self.VerList)==1:
			self.Adj_matrix = np.zeros((1,1))
		else:
			col = np.zeros((len(self.VerList)-1,1))
			row = np.zeros((1,len(self.VerList)))
			self.Adj_matrix = np.column_stack((self.Adj_matrix,col))
			self.Adj_matrix = np.row_stack((self.Adj_matrix,row))

	#新增一个点间关系
	def addEdge(self,x):
		for f,t,w in x:
			if len(self.VerList)<f or len(self.VerList)<t:
				print("相关点出错")
				return 0
			self.Adj_matrix[f][t] = w

	def Ver(self):
		return self.VerList.keys()

	#深度优先
	def depth_first(self, e):
		mask = []
		def run(e):
			mask.append(e)
			if len(mask) == 1:
				print(self.VerList[e])
			for i in range(len(self.Adj_matrix[e])):
				while self.Adj_matrix[e][i] != 0 and i not in mask:
					print(self.VerList[i])
					run(i)
			if len(mask) != len(self.VerList):
				for i in self.VerList.keys():
					if int(i) not in mask:
						print(self.VerList[int(i)])
						run(int(i))
		return run(e)

	#最小生成树
	def Kruskal(self,edge):
	    vnum=self.Ver()
	    reps=[i for i in range(len(vnum))]
	    mst = []
	    edges = copy.deepcopy(edge)
	    edges.sort(key=lambda x:x[2])
	    #print(edges)
	    for vi,vj,w in edges:
	        if reps[vi]!=reps[vj]:
	            mst.append((vi,vj,w))
	            if len(mst)==len(vnum)-1:
	                break
	            rep,orep=reps[vi],reps[vj]
	            for i in range(len(vnum)):
	                if reps[i]==orep:
	                    reps[i]=rep
	    Kru_matrix = np.zeros((len(vnum),len(vnum)))
	    for f,t,w in mst:
	    	Kru_matrix[f][t] = w
	    	# Kru_matrix[t][f] = w
	    print(Kru_matrix)



	#输出点和邻接矩阵
	def output(self):
		print(self.VerList)
		print(self.Adj_matrix)
		





class Graph_list(object):
	"""docstring for Graph_list"""
	def __init__(self):
		self.VerList = {}
		self.Adj_list = {}
		
	def addVertex(self, num, val=None):
		ver = Vertex(num,val)
		self.VerList[ver.num] = ver.val

	def addEdge(self, x):
		for f,t,w in x:
			if len(self.VerList)<f or len(self.VerList)<t:
				print("相关点出错")
				return 0
			if f not in self.Adj_list.keys():
				self.Adj_list[f] = {}
			self.Adj_list[f][t] = w
	def Ver(self):
		return self.VerList.keys()
	#输出点和临界表（用字典储存的）
	def output(self):
		print(self.VerList)
		print(self.Adj_list)

if __name__ == '__main__':

  name = ['ccy','yjt','zhy','zws','ssl']
  new = Graph_matrix()
  for i,j in enumerate(name):
    new.addVertex(i,j)
  edge = [(0,2,6),(0,1,6),(2,1,3),(2,3,1),(3,0,5),(1,2,5),(1,4,7),(4,3,10),\
      (1,0,5),(0,3,10),(0,4,8),(1,3,4),(2,0,11),(2,4,5),(3,1,10),(3,2,9),\
      (3,4,6),(4,0,6),(4,1,4),(4,2,8)]
  new.addEdge(edge)
  new.output()
  new.depth_first(2)
  print('-----分割线-----')
  new.depth_first(0)
  new.Kruskal(edge)




{0: 'ccy', 1: 'yjt', 2: 'zhy', 3: 'zws', 4: 'ssl'}
[[ 0.  6.  6. 10.  8.]
 [ 5.  0.  5.  4.  7.]
 [11.  3.  0.  1.  5.]
 [ 5. 10.  9.  0.  6.]
 [ 6.  4.  8. 10.  0.]]
zhy
ccy
yjt
zws
ssl
-----分割线-----
ccy
yjt
zhy
zws
ssl
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 0. 1. 0.]
 [5. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]]


In [ ]:
import numpy as np
w = np.full((9,9),np.inf)
print(w)

[[inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf]]
